version: '3'

services:
  database:
    image: postgres:14.3
    restart: always
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    container_name: system_of_control
    volumes:
      - ./localDB:/var/lib/postgresql/data